#!/bin/sh

BOOTAPPEND=$(cat chroot/etc/webc/boot-cmdline | grep -v "^#" | head -n 1)

lb config noauto --clean \
	--bootappend-live "$BOOTAPPEND homepage=http://play.playr.biz/ keep_append=homepage=http://play.playr.biz/ fetch-revision=production keep_append=fetch-revision=production debug keep_append=debug" \
	--parent-mirror-chroot "http://http.debian.net/debian/" \
	--parent-mirror-binary "http://http.debian.net/debian/" \
	--binary-filesystem fat32 \
	-k "686-pae" \
	-a i386 \
	--parent-archive-areas "main contrib non-free" \
	--mode progress-linux --distribution cairon-backports \
	--debian-installer false \
	--debian-installer-gui false \
	--apt-indices false \
	--iso-publisher "http://webconverger.com" \
	--iso-volume "Webconverger" \
	--iso-application "Webconverger" \
	--archive-areas "main contrib non-free" \
	--apt-recommends false \
	--memtest none \
	--source false \
	--hdd-size 1022 \
	${@}
